// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZk5XUZ-OibURUEkGMpTkZn0-C_SGS_Og',
    appId: '1:473662929769:web:43a034a893791d3fea9bf8',
    messagingSenderId: '473662929769',
    projectId: 'flutterbasicapp-12d34',
    authDomain: 'flutterbasicapp-12d34.firebaseapp.com',
    storageBucket: 'flutterbasicapp-12d34.firebasestorage.app',
    measurementId: 'G-CB4X8GJY9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ_iB87akR8c7dYurRGIWnRj9P6T3Yw9o',
    appId: '1:473662929769:android:5a01a1cab02e2685ea9bf8',
    messagingSenderId: '473662929769',
    projectId: 'flutterbasicapp-12d34',
    storageBucket: 'flutterbasicapp-12d34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANacsICBArijwelO_AG8EpCni8sNBQNQY',
    appId: '1:473662929769:ios:71cb5efd254da840ea9bf8',
    messagingSenderId: '473662929769',
    projectId: 'flutterbasicapp-12d34',
    storageBucket: 'flutterbasicapp-12d34.firebasestorage.app',
    iosBundleId: 'com.example.fireBaseBasicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANacsICBArijwelO_AG8EpCni8sNBQNQY',
    appId: '1:473662929769:ios:71cb5efd254da840ea9bf8',
    messagingSenderId: '473662929769',
    projectId: 'flutterbasicapp-12d34',
    storageBucket: 'flutterbasicapp-12d34.firebasestorage.app',
    iosBundleId: 'com.example.fireBaseBasicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZk5XUZ-OibURUEkGMpTkZn0-C_SGS_Og',
    appId: '1:473662929769:web:1f622f35a39ad452ea9bf8',
    messagingSenderId: '473662929769',
    projectId: 'flutterbasicapp-12d34',
    authDomain: 'flutterbasicapp-12d34.firebaseapp.com',
    storageBucket: 'flutterbasicapp-12d34.firebasestorage.app',
    measurementId: 'G-TJSG30DZNQ',
  );
}
